version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: saturday
    time: 02:00
    timezone: Australia/Brisbane
  groups:
    pip:
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: saturday
    time: 02:00
    timezone: Australia/Brisbane
  groups:
    github-actions:
      patterns:
      - '*'
