[project]
name = "slackmoji"
version = "0.1.0"
description = "Dumping emoji all the live long day"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.14",
    "ty>=0.0.39",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"